name: my first workflow
on : push
jobs :
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: welcome message
              run : echo "Hello There"
            - name: list file
              run : ls
            - name: print README.md
              run : cat README.md